name: Release
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - run: uv sync --group dev
      - run: uv run pyinstaller winks.spec
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          prerelease: true
          make_latest: true
          files: dist/winks.exe
